services:
  - type: web
    name: nestjs-server
    env: node
    branch: main
    plan: free
    buildCommand: 'npm install && npm run build'
    startCommand: 'npm run start:prod'
    envVars:
      - key: NODE_ENV
        value: production
